version: '3'
services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
